# Generated by Django 6.1.1 on 2026-09-26 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('id_comprobante_referencia', models.IntegerField(blank=True, null=True)),
                ('fecha_compra', models.DateTimeField()),
                ('numero_autorizacion', models.CharField(blank=True, max_length=49, null=True)),
                ('secuencial', models.CharField(blank=True, max_length=9, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('impuesto1', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('impuesto2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo', models.CharField(default='C', help_text='C=COMPRA, P=PEDIDO', max_length=1)),
                ('estado_compra', models.CharField(default='G', help_text='G=GENERADO, A=APROBADO P=PAGADO, R=RECIBIDO EN BODEGA', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seguridad.persona')),
                ('numero_cuenta', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('seguridad.persona',),
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('id_producto', models.IntegerField()),
                ('id_promocion', models.IntegerField(blank=True, null=True)),
                ('nombre_producto', models.CharField(max_length=250)),
                ('numero_serie', models.CharField(blank=True, max_length=200, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fk_codigo_compra', models.ForeignKey(db_column='fk_codigo_comprobante', on_delete=django.db.models.deletion.PROTECT, related_name='FK_COMPRA_DETALLE', to='compra.compra')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('forma', models.CharField(default='C', help_text='C=CONTADO, D=DIFERIDO', max_length=1)),
                ('fecha', models.DateField()),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=8)),
                ('numero_cuotas', models.IntegerField()),
                ('porcentaje_intereses', models.DecimalField(decimal_places=2, max_digits=8)),
                ('entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('monto_cuota', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado_pago', models.CharField(help_text='G=GENERADO, P=PENDIENTE, C=COMPLETADO', max_length=1)),
                ('fk_codigo_compra', models.ForeignKey(db_column='fk_codigo_compra', on_delete=django.db.models.deletion.PROTECT, related_name='FK_COMPRA_PAGO', to='compra.compra')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PagoDetalle',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('id_movimiento_caja', models.IntegerField(blank=True, null=True)),
                ('numero_cuota', models.IntegerField()),
                ('fecha_cuota', models.DateField()),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('monto_pago_efectivo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monto_pago_transferencia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monto_pago_cheque', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monto_pago_comprobante', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('id_comprobante', models.IntegerField(blank=True, null=True)),
                ('monto_pago_tarjeta', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tipo_tarjeta', models.CharField(blank=True, help_text='C=CREDITO, D=DEBITO', max_length=1, null=True)),
                ('monto_pago_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('archivo1', models.BinaryField(blank=True, null=True)),
                ('archivo2', models.BinaryField(blank=True, null=True)),
                ('fk_codigo_pago', models.ForeignKey(db_column='fk_codigo_pago', on_delete=django.db.models.deletion.PROTECT, related_name='FK_PAGO_DETALLE', to='compra.pago')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='fk_codigo_proveedor',
            field=models.ForeignKey(db_column='fk_codigo_proveedor', on_delete=django.db.models.deletion.PROTECT, related_name='FK_PROVEEDOR_COMPRA', to='compra.proveedor'),
        ),
    ]
