# Generated by Django 6.1.1 on 2026-09-26 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_auxiliar', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('grupo', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=200)),
                ('representante', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=13)),
                ('fecha_constitucion', models.DateField(auto_now_add=True)),
                ('calle_principal', models.CharField(max_length=100)),
                ('calle_secundaria', models.CharField(max_length=100)),
                ('numero_casa', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=9)),
                ('obligado_contabilidad', models.CharField(default='N', help_text='S=SI, N=NO', max_length=1)),
                ('facturacion_electronica', models.CharField(default='N', help_text='S=SI, N=NO', max_length=1)),
                ('logotipo', models.BinaryField(blank=True, null=True)),
                ('certificado', models.BinaryField(blank=True, null=True)),
                ('id_localidad', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoSanguineo',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instruccion',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_padre', models.IntegerField(blank=True, null=True)),
                ('codigo_auxiliar', models.CharField(blank=True, max_length=25, null=True)),
                ('nombre', models.CharField(max_length=250)),
                ('nivel', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_padre', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('nivel', models.IntegerField()),
                ('orden', models.IntegerField()),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('estilo_clase', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=13)),
                ('razon_social', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fotografia', models.BinaryField(blank=True, null=True)),
                ('mail1', models.EmailField(blank=True, max_length=50, null=True)),
                ('mail2', models.EmailField(blank=True, max_length=50, null=True)),
                ('telefono1', models.CharField(blank=True, max_length=9, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=9, null=True)),
                ('celular1', models.CharField(blank=True, max_length=10, null=True)),
                ('celular2', models.CharField(blank=True, max_length=10, null=True)),
                ('calle_principal', models.CharField(blank=True, max_length=50, null=True)),
                ('calle_secundaria', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_casa', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(help_text='P=PERSONA NATURAL, S=SOCIEDAD', max_length=1)),
                ('ubicacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fk_codigo_estado_civil', models.ForeignKey(db_column='fk_codigo_estado_civil', on_delete=django.db.models.deletion.PROTECT, related_name='codigo_estado_civil', to='seguridad.estadocivil')),
                ('fk_codigo_genero', models.ForeignKey(db_column='fk_codigo_genero', on_delete=django.db.models.deletion.PROTECT, related_name='codigo_generos', to='seguridad.genero')),
                ('fk_codigo_grupo_sanguineo', models.ForeignKey(db_column='fk_codigo_grupo_sanguineo', on_delete=django.db.models.deletion.PROTECT, related_name='codigo_grupo_sanguineo', to='seguridad.gruposanguineo')),
                ('fk_codigo_instruccion', models.ForeignKey(db_column='fk_codigo_instruccion', on_delete=django.db.models.deletion.PROTECT, related_name='codigo_instruccion', to='seguridad.instruccion')),
                ('fk_codigo_localidad', models.ForeignKey(db_column='fk_codigo_localidad', on_delete=django.db.models.deletion.PROTECT, related_name='codigo_localidad', to='seguridad.localidad')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persona', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_auxiliar', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('permisos', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seguridad.persona')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
            bases=('seguridad.persona',),
        ),
        migrations.CreateModel(
            name='RolMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_codigo_menu', models.ForeignKey(db_column='fk_codigo_menu', on_delete=django.db.models.deletion.PROTECT, related_name='FK_MENU_ROL', to='seguridad.menu')),
                ('fk_codigo_rol', models.ForeignKey(db_column='fk_codigo_rol', on_delete=django.db.models.deletion.PROTECT, related_name='FK_ROL_MENU', to='seguridad.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('id_localidad', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('gerente', models.CharField(max_length=200)),
                ('secuencial_sucursal', models.CharField(max_length=200)),
                ('calle_principal', models.CharField(max_length=100)),
                ('calle_secundaria', models.CharField(max_length=100)),
                ('numero_casa', models.CharField(max_length=50)),
                ('fk_codigo_empresa', models.ForeignKey(db_column='fk_codigo_empresa', on_delete=django.db.models.deletion.PROTECT, related_name='empresa_sucursales', to='seguridad.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('valor', models.CharField(max_length=50)),
                ('fk_codigo_configuracion', models.ForeignKey(db_column='fk_codigo_configuracion', on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_empresas', to='seguridad.configuracion')),
                ('fk_codigo_empresa', models.ForeignKey(db_column='fk_codigo_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='empresa_configuraciones', to='seguridad.empresa')),
            ],
            options={
                'db_table': 'empresa_configuracion',
                'unique_together': {('fk_codigo_empresa', 'fk_codigo_configuracion')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_codigo_rol', models.ForeignKey(db_column='fk_codigo_rol', on_delete=django.db.models.deletion.PROTECT, related_name='FK_ROL_USUARIO', to='seguridad.rol')),
                ('fk_codigo_usuario', models.ForeignKey(db_column='fk_codigo_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='FK_USUARIO_ROL', to='seguridad.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='fk_codigo_sucursal',
            field=models.ForeignKey(db_column='fk_codigo_sucursal', on_delete=django.db.models.deletion.PROTECT, related_name='FK_SUCURSAL_USUARIO', to='seguridad.sucursal'),
        ),
        migrations.CreateModel(
            name='IngresoSistema',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('ip', models.CharField(blank=True, max_length=25, null=True)),
                ('validador', models.CharField(blank=True, max_length=25, null=True)),
                ('estado', models.CharField(default='G', help_text='G=GENERADO, O=OCUPADO, C=CADUCADO', max_length=1)),
                ('fk_codigo_usuario', models.ForeignKey(db_column='fk_codigo_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='FK_USUARIO_INGRESO', to='seguridad.usuario')),
            ],
        ),
    ]
