# Generated by Django 6.1.1 on 2026-09-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='A=Activo, I=Inactivo', max_length=1),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='fecha_actualiza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='A=Activo, I=Inactivo', max_length=1),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fecha_actualiza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresaconfiguracion',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='A=Activo, I=Inactivo', max_length=1),
        ),
        migrations.AlterField(
            model_name='empresaconfiguracion',
            name='fecha_actualiza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadocivil',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='A=Activo, I=Inactivo', max_length=1),
        ),
        migrations.AlterField(
            model_name='estadocivil',
            name='fecha_actualiza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genero',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='A=Activo, I=Inactivo', max_length=1),
        ),
        migrations.AlterField(
            model_name='genero',
            name='fecha_actualiza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gruposanguineo',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='A=Activo, I=Inactivo', max_length=1),
        ),
        migrations.AlterField(
            model_name='gruposanguineo',
            name='fecha_actualiza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instruccion',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='A=Activo, I=Inactivo', max_length=1),
        ),
        migrations.AlterField(
            model_name='instruccion',
            name='fecha_actualiza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='A=Activo, I=Inactivo', max_length=1),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='fecha_actualiza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='A=Activo, I=Inactivo', max_length=1),
        ),
        migrations.AlterField(
            model_name='menu',
            name='fecha_actualiza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='A=Activo, I=Inactivo', max_length=1),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_actualiza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='A=Activo, I=Inactivo', max_length=1),
        ),
        migrations.AlterField(
            model_name='rol',
            name='fecha_actualiza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='A=Activo, I=Inactivo', max_length=1),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='fecha_actualiza',
            field=models.DateField(blank=True, null=True),
        ),
    ]
