# Generated by Django 6.1.1 on 2026-09-26 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('efectivo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transferencia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cheque', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tarjeta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo_tarjeta', models.CharField(default='C', help_text='C=CRÉDITO, D=DÉBITO', max_length=1)),
                ('comprobante', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_comprobante', models.IntegerField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado_caja', models.CharField(default='C', help_text='A=ABIERTO, C=CERRADO, R=ARQUEO', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Financiera',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_auxiliar', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(default='I', help_text='A=APERTURA, I=INGRESO, R=ARQUEO, G=GASTO, C=CIERRE', max_length=1)),
                ('detalle', models.CharField(max_length=25)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('efectivo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transferencia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cheque', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tarjeta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo_tarjeta', models.CharField(default='C', help_text='C=CRÉDITO, D=DÉBITO', max_length=1)),
                ('comprobante', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_comprobante', models.IntegerField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('diferencia_efectivo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('diferencia_transferencia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('diferencia_cheque', models.DecimalField(decimal_places=2, max_digits=8)),
                ('diferencia_tarjeta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('diferencia_comprobante', models.DecimalField(decimal_places=2, max_digits=8)),
                ('diferencia_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caja.caja')),
                ('financiera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='caja.financiera')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
