# Generated by Django 6.1.1 on 2026-09-26 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_padre', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('id_texto_Empresa', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fk_codigo_sucursal', models.IntegerField(blank=True, null=True)),
                ('codigo_padre', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(default='B', help_text='B=BODEGA, A=ALMACEN', max_length=1)),
                ('categoria', models.CharField(default='F', help_text='F=FISICO, L=LOGICO', max_length=1)),
                ('ubicacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CentroProducto',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fk_codigo_centro_costo', models.IntegerField(blank=True, null=True)),
                ('fk_codigo_producto', models.IntegerField(blank=True, null=True)),
                ('stock', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('porcentaje_cliente', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precio_venta_cliente', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('porcentaje_distribuidor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precio_venta_distribuidor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('porcentaje_promocion', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precio_venta_promocion', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('id_empresa', models.IntegerField(blank=True, null=True)),
                ('id_comprobante', models.IntegerField(blank=True, null=True)),
                ('tipo_movimiento', models.CharField(default='I', help_text='I=INGRESO, S=SALIDA', max_length=1)),
                ('id_bodega', models.IntegerField(blank=True, null=True)),
                ('id_compra', models.IntegerField(blank=True, null=True)),
                ('id_producto', models.IntegerField(blank=True, null=True)),
                ('id_venta', models.IntegerField(blank=True, null=True)),
                ('detalle', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('costo_unitario_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('costo_total_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cantidad_salida', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('costo_unitario_salida', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('costo_total_salida', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fecha_contable', models.DateField(blank=True, null=True)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('id_texto_Empresa', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('abreviatura', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('id_texto_Empresa', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('id_empresa', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=250)),
                ('modelo', models.CharField(max_length=100)),
                ('stock_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stock_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stock', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('porcentaje_cliente', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precio_venta_cliente', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('porcentaje_distribuidor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precio_venta_distribuidor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('porcentaje_promocion', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precio_venta_promocion', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estado_promocion', models.CharField(default='N', help_text='N=NO, S=SI', max_length=1)),
                ('tipo', models.CharField(default='P', help_text='P=PRODUCTO, S=SERVICIO', max_length=1)),
                ('caracteristica', models.CharField(blank=True, max_length=100, null=True)),
                ('fk_codigo_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categoria', to='inventario.categoria')),
                ('fk_codigo_marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marca', to='inventario.marca')),
                ('fk_codigo_unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidad_medida', to='inventario.unidadmedida')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('principal', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
