# Generated by Django 6.1.1 on 2026-09-27 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centroproducto',
            name='fk_codigo_centro_costo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.centrocosto'),
        ),
        migrations.AlterField(
            model_name='centroproducto',
            name='fk_codigo_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centros', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='centroproducto',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
