# Generated by Django 6.1.1 on 2026-09-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_centroproducto_fk_codigo_centro_costo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='A=Activo, I=Inactivo', max_length=1),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha_actualiza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centrocosto',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='A=Activo, I=Inactivo', max_length=1),
        ),
        migrations.AlterField(
            model_name='centrocosto',
            name='fecha_actualiza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centroproducto',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='A=Activo, I=Inactivo', max_length=1),
        ),
        migrations.AlterField(
            model_name='centroproducto',
            name='fecha_actualiza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='A=Activo, I=Inactivo', max_length=1),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='fecha_actualiza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='A=Activo, I=Inactivo', max_length=1),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='fecha_actualiza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='A=Activo, I=Inactivo', max_length=1),
        ),
        migrations.AlterField(
            model_name='marca',
            name='fecha_actualiza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='A=Activo, I=Inactivo', max_length=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_actualiza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='A=Activo, I=Inactivo', max_length=1),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='fecha_actualiza',
            field=models.DateField(blank=True, null=True),
        ),
    ]
