# Generated by Django 6.1.1 on 2026-09-26 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seguridad.persona')),
                ('tiene_credito', models.CharField(default='N', help_text='S=SI, N=NO', max_length=1)),
                ('dias_mora', models.IntegerField(blank=True, null=True)),
                ('monto_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('saldo_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('deuda_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tipo_cliente', models.CharField(blank=True, default='N', help_text='N=NORMAL, M=MAYORISTA', max_length=1, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('seguridad.persona',),
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('forma', models.CharField(default='C', help_text='C=CONTADO, D=DIFERIDO', max_length=1)),
                ('fecha', models.DateField()),
                ('total_comprobante', models.DecimalField(decimal_places=2, max_digits=8)),
                ('numero_cuotas', models.IntegerField()),
                ('porcentaje_intereses', models.DecimalField(decimal_places=2, max_digits=8)),
                ('entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('monto_cuota', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado_cobro', models.CharField(help_text='G=GENERADO, P=PENDIENTE, C=COMPLETADO', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CobroDetalle',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('id_movimiento_caja', models.IntegerField(blank=True, null=True)),
                ('numero_cuota', models.IntegerField()),
                ('fecha_cuota', models.DateField()),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_cobro', models.DateField(blank=True, null=True)),
                ('monto_cobro_efectivo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monto_cobro_transferencia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monto_cobro_cheque', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monto_cobro_comprobante', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('id_comprobante', models.IntegerField(blank=True, null=True)),
                ('monto_cobro_tarjeta', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tipo_tarjeta', models.CharField(blank=True, help_text='C=CREDITO, D=DEBITO', max_length=1, null=True)),
                ('monto_cobro_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('archivo1', models.BinaryField(blank=True, null=True)),
                ('archivo2', models.BinaryField(blank=True, null=True)),
                ('fk_codigo_cobro', models.ForeignKey(db_column='fk_codigo_cobro', on_delete=django.db.models.deletion.PROTECT, related_name='FK_COBRO_DETALLE', to='venta.cobro')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('estado', models.CharField(default='A', help_text='A=Activo, I=Inactivo', max_length=1)),
                ('usuario_crea', models.IntegerField()),
                ('usuario_actualiza', models.IntegerField(blank=True, null=True)),
                ('fecha_crea', models.DateField(auto_now_add=True)),
                ('fecha_actualiza', models.DateField(auto_now=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('id_comprobante_referencia', models.IntegerField(blank=True, null=True)),
                ('fecha_emision', models.DateTimeField()),
                ('clave_acceso', models.CharField(max_length=49)),
                ('numero_autorizacion', models.CharField(blank=True, max_length=49, null=True)),
                ('estado_transmision', models.CharField(default='GEN', help_text='GEN=GENERADO, TRA=TRANSMITIDO, AUT=AUTORIZADO, NAT=NO AUTORIZADO', max_length=3)),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('tipo_comprobante', models.CharField(default='01', help_text='01=FACTURA, 03=LIQUIDACION COMPRA, 04=NOTA CREDITO, 05=NOTA DEBITO, 06=GUIA REMISION, 07=GUIA REMISION', max_length=2)),
                ('tipo_ambiente', models.CharField(default='1', help_text='1=PRUEBAS, 2=PRODUCCION', max_length=1)),
                ('serie', models.CharField(max_length=6)),
                ('secuencial', models.CharField(max_length=9)),
                ('codigo_numerico', models.CharField(max_length=8)),
                ('tipo_emision', models.CharField(default='1', help_text='1=NORMAL', max_length=1)),
                ('digito_verificador', models.CharField(max_length=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('impuesto1', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('impuesto2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo', models.CharField(default='C', help_text='C=COMPROBANTE, P=PROFORMA', max_length=1)),
                ('estado_comprobante', models.CharField(help_text='G=GENERADO, P=PAGADO, D=DESPACHADO', max_length=1)),
                ('fk_codigo_cliente', models.ForeignKey(db_column='fk_codigo_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='FK_CLIENTE_COMPROBANTE', to='venta.cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cobro',
            name='fk_codigo_comprobante',
            field=models.ForeignKey(db_column='fk_codigo_comprobante', on_delete=django.db.models.deletion.PROTECT, related_name='FK_COMPROBANTE_COBRO', to='venta.comprobante'),
        ),
        migrations.CreateModel(
            name='ComprobanteDetalle',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('id_producto', models.IntegerField()),
                ('id_promocion', models.IntegerField(blank=True, null=True)),
                ('nombre_producto', models.CharField(max_length=250)),
                ('numero_serie', models.CharField(blank=True, max_length=200, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo_precio', models.CharField(default='C', help_text='C=CLIENTE, D=DISTRIBUIDOR, P=PROMOCION', max_length=1)),
                ('fk_codigo_comprobante', models.ForeignKey(db_column='fk_codigo_comprobante', on_delete=django.db.models.deletion.PROTECT, related_name='FK_COMPROBANTE_DETALLE', to='venta.cliente')),
            ],
        ),
    ]
