# Generated by Django 6.1.1 on 2026-09-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='A=Activo, I=Inactivo', max_length=1),
        ),
        migrations.AlterField(
            model_name='cobro',
            name='fecha_actualiza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cobrodetalle',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='A=Activo, I=Inactivo', max_length=1),
        ),
        migrations.AlterField(
            model_name='cobrodetalle',
            name='fecha_actualiza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', help_text='A=Activo, I=Inactivo', max_length=1),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='fecha_actualiza',
            field=models.DateField(blank=True, null=True),
        ),
    ]
